name: osx_11_0

on: [push, pull_request]

env:
  CI_MAKE: make -f .travis.mk

jobs:
  osx_11_0:
    # We want to run on external PRs, but not on our own internal PRs
    # as they'll be run by the push to the branch.
    if: github.event_name == 'push' ||
        github.event.pull_request.head.repo.full_name != github.repository

    runs-on: macos-11.0

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          submodules: recursive
      - name: look at /usr/lib/
        run: ls -hal /usr/lib/
      - name: look at .../SDKs/MacOSX11.0.sdk/usr/lib/
        run: ls -hal /Applications/Xcode_12.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk/usr/lib/
      - name: test
        run: ${CI_MAKE} test_osx_github_actions
      - name: artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: osx_11_0
          retention-days: 1000000
          path: CMakeFiles
